<script setup lang="ts">
  import { useDisplay } from 'vuetify'
  import numberFormater from '../utils/numberFormater'
  import LineChartComponent from './LineChartComponent.vue'
  import TooltipComponent from '~/components/common/TooltipComponent.vue'

  interface Props {
    dataDaysChartData?: number[]
    dataDaysLastAndProgress?: {
      lastValue?: string
      progress?: string
    }
    dataDaysChartLabels?: string[]
    dataDays30DaysTotal?: number
  }

  const props = withDefaults(defineProps<Props>(), {
    dataDaysChartData: () => [],
    dataDaysLastAndProgress: () => ({
      lastValue: '0',
      progress: '0'
    }),
    dataDaysChartLabels: () => [],
    dataDays30DaysTotal: 0
  })

  const { trackGAevent } = useGAevents()
  const display = ref(useDisplay())
  const weatherStationDaysCardTitle = ref('Weather Station-Days')
  const weatherStationDaysCardLast30DaysText = ref('Last 30 Days')
  const weatherStationDaysCardTotalText = ref('TOTAL')
  const weatherStationDaysCardLastDayText = ref('LAST DAY')

  const dataDaysMessage = ref(
    'The amount of daily weather data generated by stations. One station generates one weather-station-day if it provides high quality data throughout the day.'
  )

  const tooltipTitle = ref('Weather Station-Days')

  const responsiveTextStyles = computed(() => {
    return display.value.smAndDown
      ? { 'font-size': '1.402rem', 'font-weight': 700 }
      : { 'font-size': '1.705rem', 'font-weight': 700 }
  })

  const nFormat = (number: number) => {
    return numberFormater.nFormatter(number)
  }
</script>

<template>
  <VSheet
    color="top"
    style="border-radius: 16px"
    :class="display.smAndDown ? `mb-3` : `mb-4`"
    elevation="4"
  >
    <div class="px-2 pt-2 text-body-2 d-flex align-center justify-space-between">
      <div style="font-size: 1.094rem; font-weight: 700" class="text-text pl-2 pt-1">
        {{ weatherStationDaysCardTitle }}
      </div>
      <div
        @mouseenter="trackGAevent('clickInfoIcon', { ITEM_ID: 'data_days' })"
        @click="trackGAevent('clickInfoIcon', { ITEM_ID: 'data_days' })"
      >
        <TooltipComponent
          :message="dataDaysMessage"
          :container="'any'"
          :tooltip-title="tooltipTitle"
        />
      </div>
    </div>
    <VRow class="ma-0 pa-0 pl-5 pt-6 d-flex pb-4 pr-7">
      <VCol class="ma-0 pa-0" cols="9">
        <VRow class="ma-0 pa-0">
          <LineChartComponent
            :data="props.dataDaysChartData"
            class="pr-11 pl-4"
          ></LineChartComponent>
          <VRow class="ma-0 pa-0 d-flex justify-space-between pr-6 pt-2">
            <div class="text-darkGrey text-uppercase" style="font-size: 0.778rem">
              {{ props.dataDaysChartLabels[0] }}
            </div>
            <div class="text-darkGrey text-uppercase" style="font-size: 0.778rem">
              {{ props.dataDaysChartLabels[1] }}
            </div>
          </VRow>
        </VRow>
      </VCol>
      <VCol class="ma-0 pa-0 d-flex align-center justify-center" cols="3">
        <div :style="responsiveTextStyles">
          <div class="text-text d-flex justify-center" style="line-height: 120%">
            {{ nFormat(props.dataDays30DaysTotal) }}
          </div>
          <div
            class="text-darkGrey d-flex justify-center"
            :style="
              display.smAndDown
                ? { 'font-size': '0.691rem', 'font-weight': 400 }
                : { 'font-size': '0.778rem', 'font-weight': 400 }
            "
          >
            {{ weatherStationDaysCardLast30DaysText }}
          </div>
        </div>
      </VCol>
    </VRow>
    <VRow class="px-2 pb-2 ma-0">
      <VCol class="pa-0 ma-0" cols="6">
        <VSheet class="px-4 pb-3 pt-3 ma-0 mr-1" color="layer1" style="border-radius: 8px">
          <div class="d-flex justify-space-between align-center mb-4">
            <div class="text-text text-caption">{{ weatherStationDaysCardTotalText }}</div>
          </div>
          <div :style="responsiveTextStyles">
            <div class="text-text d-flex justify-start">
              {{ props.dataDaysLastAndProgress.lastValue }}
            </div>
          </div>
        </VSheet>
      </VCol>
      <VCol class="pa-0 ma-0" cols="6">
        <VSheet class="px-4 pb-3 pt-3 ma-0 ml-1" color="layer1" style="border-radius: 8px">
          <div class="d-flex justify-space-between align-center mb-4">
            <div class="text-text text-caption">{{ weatherStationDaysCardLastDayText }}</div>
          </div>
          <div :style="responsiveTextStyles">
            <div class="text-rewardVeryHigh d-flex justify-start">
              +{{ props.dataDaysLastAndProgress.progress }}
            </div>
          </div>
        </VSheet>
      </VCol>
    </VRow>
  </VSheet>
</template>
