<script setup lang="ts">
  import { useTheme } from 'vuetify'
  import dayjs from 'dayjs'
  import timezone from 'dayjs/plugin/timezone'
  import { selectValidationScoreColor } from '../utils/selectScoreColor'
  import type { Device, LatestTokens, WeeklyMonthlyTokens } from '../types/device'
  import RewardsMessage from './RewardsMessage.vue'
  import TotalStationRewards from './RewardsWidgets/TotalStationRewards.vue'
  import DailyRewards from './RewardsWidgets/DailyRewards.vue'
  import WeeklySteak from './RewardsWidgets/WeeklyStreak.vue'
  import MainnetBanner from './RewardsWidgets/MainnetBanner.vue'
  import EmptyRewards from './RewardsWidgets/EmptyRewards.vue'
  import wxmApi from '~/api/wxmApi'
  import TooltipComponent from '~/components/common/TooltipComponent.vue'
  dayjs.extend(timezone)

  interface Props {
    device?: Device
  }

  const props = withDefaults(defineProps<Props>(), {
    device: () => ({
      cellIndex: '',
      id: '',
      isActive: true,
      lastWeatherStationActivity: '',
      name: '',
      profile: '',
      timezone: '',
      current_weather: {
        dew_point: 0,
        feels_like: 0,
        humidity: 0,
        icon: 'not_available',
        precipitation: 0,
        precipitation_accumulated: 0,
        solar_irradiance: 0,
        pressure: 0,
        temperature: 0,
        timestamp: '',
        uv_index: 0,
        wind_direction: 0,
        wind_gust: 0,
        wind_speed: 0
      }
    })
  })

  const emit = defineEmits(['loadingRewardsTab'])

  const theme = useTheme()

  // rewards stuff
  const deviceTokens = ref()
  const validationScoreColor = ref()
  const total = ref('')
  const actualReward = ref('')
  const lostRewards = ref(0)
  const periodMaxReward = ref('')
  const rewardScore = ref(100)
  const timelineTimestamp = ref()
  const timelineColorsArray = ref()
  const tokensTimestamp = ref('')
  const tokensFromDate = ref('')
  const tokensToDate = ref('')
  const showPeriod = ref('Latest')
  const tokenBtnOutline = ref(true)
  const latestButtonText = ref('Latest')
  const last7DButtonText = ref('Last 7D')
  const last30DButtonText = ref('Last 30D')
  const rewardScoreText = ref('Reward Score')
  const maxRewardsText = ref('Max Rewards')

  const maxRewardTooltipTitle = ref('Max Rewards')
  const maxRewardTooltipMessage = ref(
    'The maximum rewards you could earn in that reward distribution if you had a perfect 100% reward score.'
  )
  const rewardScoreTooltipTitle = ref('Reward Score')
  const rewardScoreTooltipMessage = ref(
    'A score from 0-1 (0-100%) which takes into account multiple factors in order to calculate the rewards you will earn on any given date.'
  )
  const timelineTooltipMessage = ref(
    'The amount of daily weather data generated by stations. One station generates one weather-station-day if it provides high quality data throughout the day.'
  )

  const timelineTooltipTitle = ref('Timeline')

  const timestamp = computed(() => {
    return `${dayjs(tokensTimestamp.value).utc().format('MMM D, h:mm A')} (UTC)`
  })

  const timelineTs = computed(() => {
    return `Timeline for, ${dayjs(timelineTimestamp.value).utc().format('MMMM D YYYY')} (UTC)`
  })

  const tokensFromDateTs = computed(() => {
    return `${dayjs(tokensFromDate.value).utc().format('MMM D')}`
  })
  const tokensToDateTs = computed(() => {
    return `${dayjs(tokensToDate.value).utc().format('MMM D')}`
  })

  const tokensTimelinePeriod = computed(() => {
    return `Timeline for, ${dayjs(tokensFromDate.value).utc().format('MMM D')} - ${dayjs(
      tokensToDate.value
    )
      .utc()
      .format('MMM D')} (UTC)`
  })

  const calcedGraphWidth = computed(() => {
    return calcGraphWidth(showPeriod.value)
  })

  const calcGraphWidth = (period: string) => {
    if (period === 'Latest') {
      return '8.8px'
    }
    if (period === 'Last 7D') {
      return '20px'
    }
    if (period === 'Last 30D') {
      return '6.27px'
    }
  }

  const selectPercentageBadgeColor = (rewardScore: number) => {
    const diffMax = 100 - rewardScore

    if (diffMax === 0) {
      return theme.current.value.colors.successTint
    }
    if (diffMax >= 1 && diffMax <= 29) {
      return theme.current.value.colors.warningTint
    }
    if (diffMax > 29) {
      return theme.current.value.colors.errorTint
    } else {
      return '#BAC7CB'
    }
  }

  const countDecimals = (number: number) => {
    if (Number.isInteger(number)) {
      return 0
    } else {
      return number.toString().split('.')[1].length
    }
  }
  const removeTrailingZeros = (number: string) => {
    return Number(number.toString()) * 1
  }
  const computeStringNumber = (number: string) => {
    const num = number
    const trailedNumber = removeTrailingZeros(num)
    const decimals = countDecimals(trailedNumber)
    if (decimals <= 2) {
      return Number(num).toFixed(2).toString()
    }
    if (decimals > 2 && decimals <= 5) {
      return num.substring(0, num.indexOf('.') + decimals + 1)
    } else {
      const fixedFive = num.substring(0, num.indexOf('.') + 5)
      return countDecimals(removeTrailingZeros(fixedFive)) <= 2
        ? num.substring(0, num.indexOf('.') + 2)
        : num.substring(0, num.indexOf('.') + countDecimals(removeTrailingZeros(fixedFive)) + 1)
    }
  }

  const showLatest = (deviceLatestTokens: LatestTokens) => {
    showPeriod.value = 'Latest'
    actualReward.value = `+ ${computeStringNumber(
      deviceLatestTokens.actual_reward.toString()
    )} $WXM`
    lostRewards.value = deviceLatestTokens.lost_reward
    periodMaxReward.value = computeStringNumber(deviceLatestTokens.period_max_reward.toString())
    rewardScore.value = deviceLatestTokens.reward_score
    timelineTimestamp.value = deviceLatestTokens.timeline.reference_date
    timelineColorsArray.value = deviceLatestTokens.timeline.reward_scores.map((item) => {
      return selectValidationScoreColor(item)
    })
    tokensTimestamp.value = deviceLatestTokens.timestamp
    validationScoreColor.value = selectValidationScoreColor(deviceLatestTokens.reward_score)
  }

  const showWeekly = (deviceWeeklyTokens: WeeklyMonthlyTokens) => {
    showPeriod.value = 'Last 7D'
    actualReward.value = `+ ${computeStringNumber(
      deviceWeeklyTokens.actual_reward.toString()
    )} $WXM`
    lostRewards.value = deviceWeeklyTokens.lost_rewards
    periodMaxReward.value = computeStringNumber(deviceWeeklyTokens.period_max_reward.toString())
    rewardScore.value = deviceWeeklyTokens.reward_score
    timelineColorsArray.value = deviceWeeklyTokens.timeline.reward_scores.map((item) => {
      return selectValidationScoreColor(item)
    })
    tokensFromDate.value = deviceWeeklyTokens.from_date
    tokensToDate.value = deviceWeeklyTokens.to_date
    validationScoreColor.value = selectValidationScoreColor(deviceWeeklyTokens.reward_score)
  }

  const showMonthly = (deviceMonthlyTokens: WeeklyMonthlyTokens) => {
    showPeriod.value = 'Last 30D'
    actualReward.value = `+ ${computeStringNumber(
      deviceMonthlyTokens.actual_reward.toString()
    )} $WXM`
    lostRewards.value = deviceMonthlyTokens.lost_rewards
    periodMaxReward.value = computeStringNumber(deviceMonthlyTokens.period_max_reward.toString())
    rewardScore.value = deviceMonthlyTokens.reward_score
    timelineColorsArray.value = deviceMonthlyTokens.timeline.reward_scores.map((item) => {
      return selectValidationScoreColor(item)
    })
    tokensFromDate.value = deviceMonthlyTokens.from_date
    tokensToDate.value = deviceMonthlyTokens.to_date
    validationScoreColor.value = selectValidationScoreColor(deviceMonthlyTokens.reward_score)
  }

  // get device transactions
  const getSpecificDeviceTransactions = (deviceId: string) => {
    emit('loadingRewardsTab', true)
    wxmApi
      .getDeviceTokens(deviceId)
      .then((response) => {
        if (response) {
          deviceTokens.value = response
          total.value = `${computeStringNumber(deviceTokens.value.total_rewards.toString())} $WXM`
          showLatest(deviceTokens.value.latest)
          emit('loadingRewardsTab', false)
        }
      })
      .catch(() => {
        emit('loadingRewardsTab', false)
      })
  }

  onMounted(async () => {
    await getSpecificDeviceTransactions(props.device.id)
  })
</script>

<!-- eslint-disable vue/attribute-hyphenation -->
<template>
  <div>
    <div class="py-5 px-4">
      <MainnetBanner v-if="false" :date="'14th of February'"></MainnetBanner>
      <EmptyRewards v-if="true" />
      <TotalStationRewards v-if="true" :totalRewards="1231.123" />
      <DailyRewards
        v-if="true"
        :date="'Earnings for Dec 6, 2023'"
        :dailyAmount="3.1234"
        :validationScoreColor="validationScoreColor"
        :baseRewardAmount="2.789"
        :boostAmount="1.234"
        :state="null"
      />

      <!---------------------- Weekly streak ----------------------->
      <WeeklySteak
        v-if="true"
        :date="'Base reward scores from Nov 30 to Dec 6'"
        :bar-graph-data="[
          {
            rewardScore: 20,
            timestamp: 'W'
          },
          {
            rewardScore: 30,
            timestamp: 'T'
          },
          {
            rewardScore: 40,
            timestamp: 'F'
          },
          {
            rewardScore: 10,
            timestamp: 'S'
          },
          {
            rewardScore: 70,
            timestamp: 'S'
          },
          {
            rewardScore: 100,
            timestamp: 'M'
          },
          {
            rewardScore: 80,
            timestamp: 'T'
          }
        ]"
        :fromDate="'Nov 30'"
        :toDate="'Dec 6'"
      />
    </div>
  </div>
</template>
