<script setup lang="ts">
  import { useTheme } from 'vuetify'
  import dayjs from 'dayjs'
  import timezone from 'dayjs/plugin/timezone'
  import { selectValidationScoreColor } from '../utils/selectScoreColor'
  import type { Device, LatestTokens, WeeklyMonthlyTokens } from '../types/device'
  import RewardsMessage from './RewardsMessage.vue'
  import TooltipComponent from '~/components/common/TooltipComponent.vue'
  import wxmApi from '~/api/wxmApi'

  dayjs.extend(timezone)

  interface Props {
    device?: Device
  }

  const props = withDefaults(defineProps<Props>(), {
    device: () => ({
      cellIndex: '',
      id: '',
      isActive: true,
      lastWeatherStationActivity: '',
      name: '',
      profile: '',
      timezone: '',
      current_weather: {
        dew_point: 0,
        feels_like: 0,
        humidity: 0,
        icon: 'not_available',
        precipitation: 0,
        precipitation_accumulated: 0,
        solar_irradiance: 0,
        pressure: 0,
        temperature: 0,
        timestamp: '',
        uv_index: 0,
        wind_direction: 0,
        wind_gust: 0,
        wind_speed: 0
      }
    })
  })

  const emit = defineEmits(['loadingRewardsTab'])

  const theme = useTheme()

  // rewards stuff
  const deviceTokens = ref()
  const validationScoreColor = ref()
  const total = ref('')
  const actualReward = ref('')
  const lostRewards = ref(0)
  const periodMaxReward = ref('')
  const rewardScore = ref(100)
  const timelineTimestamp = ref()
  const timelineColorsArray = ref()
  const tokensTimestamp = ref('')
  const tokensFromDate = ref('')
  const tokensToDate = ref('')
  const showPeriod = ref('Latest')
  const tokenBtnOutline = ref(true)
  const latestButtonText = ref('Latest')
  const last7DButtonText = ref('Last 7D')
  const last30DButtonText = ref('Last 30D')
  const rewardScoreText = ref('Reward Score')
  const maxRewardsText = ref('Max Rewards')

  const maxRewardTooltipTitle = ref('Max Rewards')
  const maxRewardTooltipMessage = ref(
    'The maximum rewards you could earn in that reward distribution if you had a perfect 100% reward score.'
  )
  const rewardScoreTooltipTitle = ref('Reward Score')
  const rewardScoreTooltipMessage = ref(
    'A score from 0-1 (0-100%) which takes into account multiple factors in order to calculate the rewards you will earn on any given date.'
  )
  const timelineTooltipMessage = ref(
    'The amount of daily weather data generated by stations. One station generates one weather-station-day if it provides high quality data throughout the day.'
  )

  const timelineTooltipTitle = ref('Timeline')

  const timestamp = computed(() => {
    return `${dayjs(tokensTimestamp.value).utc().format('MMM D, h:mm A')} (UTC)`
  })

  const timelineTs = computed(() => {
    return `Timeline for, ${dayjs(timelineTimestamp.value).utc().format('MMMM D YYYY')} (UTC)`
  })

  const tokensFromDateTs = computed(() => {
    return `${dayjs(tokensFromDate.value).utc().format('MMM D')}`
  })
  const tokensToDateTs = computed(() => {
    return `${dayjs(tokensToDate.value).utc().format('MMM D')}`
  })

  const tokensTimelinePeriod = computed(() => {
    return `Timeline for, ${dayjs(tokensFromDate.value).utc().format('MMM D')} - ${dayjs(
      tokensToDate.value
    )
      .utc()
      .format('MMM D')} (UTC)`
  })

  const calcedGraphWidth = computed(() => {
    return calcGraphWidth(showPeriod.value)
  })

  const calcGraphWidth = (period: string) => {
    if (period === 'Latest') {
      return '8.8px'
    }
    if (period === 'Last 7D') {
      return '20px'
    }
    if (period === 'Last 30D') {
      return '6.27px'
    }
  }

  const selectPercentageBadgeColor = (rewardScore: number) => {
    const diffMax = 100 - rewardScore

    if (diffMax === 0) {
      return theme.current.value.colors.successTint
    }
    if (diffMax >= 1 && diffMax <= 29) {
      return theme.current.value.colors.warningTint
    }
    if (diffMax > 29) {
      return theme.current.value.colors.errorTint
    } else {
      return '#BAC7CB'
    }
  }

  const countDecimals = (number: number) => {
    if (Number.isInteger(number)) {
      return 0
    } else {
      return number.toString().split('.')[1].length
    }
  }
  const removeTrailingZeros = (number: string) => {
    return Number(number.toString()) * 1
  }
  const computeStringNumber = (number: string) => {
    const num = number
    const trailedNumber = removeTrailingZeros(num)
    const decimals = countDecimals(trailedNumber)
    if (decimals <= 2) {
      return Number(num).toFixed(2).toString()
    }
    if (decimals > 2 && decimals <= 5) {
      return num.substring(0, num.indexOf('.') + decimals + 1)
    } else {
      const fixedFive = num.substring(0, num.indexOf('.') + 5)
      return countDecimals(removeTrailingZeros(fixedFive)) <= 2
        ? num.substring(0, num.indexOf('.') + 2)
        : num.substring(0, num.indexOf('.') + countDecimals(removeTrailingZeros(fixedFive)) + 1)
    }
  }

  const showLatest = (deviceLatestTokens: LatestTokens) => {
    showPeriod.value = 'Latest'
    actualReward.value = `+ ${computeStringNumber(
      deviceLatestTokens.actual_reward.toString()
    )} $WXM`
    lostRewards.value = deviceLatestTokens.lost_reward
    periodMaxReward.value = computeStringNumber(deviceLatestTokens.period_max_reward.toString())
    rewardScore.value = deviceLatestTokens.reward_score
    timelineTimestamp.value = deviceLatestTokens.timeline.reference_date
    timelineColorsArray.value = deviceLatestTokens.timeline.reward_scores.map((item) => {
      return selectValidationScoreColor(item)
    })
    tokensTimestamp.value = deviceLatestTokens.timestamp
    validationScoreColor.value = selectValidationScoreColor(deviceLatestTokens.reward_score)
  }

  const showWeekly = (deviceWeeklyTokens: WeeklyMonthlyTokens) => {
    showPeriod.value = 'Last 7D'
    actualReward.value = `+ ${computeStringNumber(
      deviceWeeklyTokens.actual_reward.toString()
    )} $WXM`
    lostRewards.value = deviceWeeklyTokens.lost_rewards
    periodMaxReward.value = computeStringNumber(deviceWeeklyTokens.period_max_reward.toString())
    rewardScore.value = deviceWeeklyTokens.reward_score
    timelineColorsArray.value = deviceWeeklyTokens.timeline.reward_scores.map((item) => {
      return selectValidationScoreColor(item)
    })
    tokensFromDate.value = deviceWeeklyTokens.from_date
    tokensToDate.value = deviceWeeklyTokens.to_date
    validationScoreColor.value = selectValidationScoreColor(deviceWeeklyTokens.reward_score)
  }

  const showMonthly = (deviceMonthlyTokens: WeeklyMonthlyTokens) => {
    showPeriod.value = 'Last 30D'
    actualReward.value = `+ ${computeStringNumber(
      deviceMonthlyTokens.actual_reward.toString()
    )} $WXM`
    lostRewards.value = deviceMonthlyTokens.lost_rewards
    periodMaxReward.value = computeStringNumber(deviceMonthlyTokens.period_max_reward.toString())
    rewardScore.value = deviceMonthlyTokens.reward_score
    timelineColorsArray.value = deviceMonthlyTokens.timeline.reward_scores.map((item) => {
      return selectValidationScoreColor(item)
    })
    tokensFromDate.value = deviceMonthlyTokens.from_date
    tokensToDate.value = deviceMonthlyTokens.to_date
    validationScoreColor.value = selectValidationScoreColor(deviceMonthlyTokens.reward_score)
  }

  // get device transactions
  const getSpecificDeviceTransactions = (deviceId: string) => {
    emit('loadingRewardsTab', true)
    wxmApi
      .getDeviceTokens(deviceId)
      .then((response) => {
        if (response) {
          deviceTokens.value = response
          total.value = `${computeStringNumber(deviceTokens.value.total_rewards.toString())} $WXM`
          showLatest(deviceTokens.value.latest)
          emit('loadingRewardsTab', false)
        }
      })
      .catch(() => {
        emit('loadingRewardsTab', false)
      })
  }

  onMounted(async () => {
    await getSpecificDeviceTransactions(props.device.id)
  })
</script>

<!-- eslint-disable vue/attribute-hyphenation -->
<template>
  <div>
    <VCard rounded="xl" class="mx-4 mb-4" elevation="2" color="layer1">
      <VCardTitle class="pa-5">
        <div class="text-body-2 text-text">Total Station Rewards</div>
        <div class="text-darkestBlue font-weight-bold" style="font-size: 1.375rem">
          {{ total }}
        </div>
      </VCardTitle>
      <VCardText class="pa-0 ma-0"
        ><VSheet class="pa-5" rounded="xl">
          <VSheet border="true" color="primary" rounded="xl" style="padding: 1px">
            <VSheet
              :border="true"
              color="blueTint"
              class="d-flex justify-space-evenly"
              rounded="xl"
            >
              <VRow class="ma-0 pa-1">
                <VCol class="ma-0 pa-0" cols="4">
                  <VBtn
                    size="small"
                    rounded="xl"
                    :color="showPeriod === 'Latest' ? 'primary' : 'blueTint'"
                    elevation="0"
                    :outlined="!tokenBtnOutline"
                    class="w-100 text-none text-body-2"
                    @click="showLatest(deviceTokens.latest)"
                  >
                    <strong :class="showPeriod === 'Latest' ? 'text-background' : 'text-primary'">
                      {{ latestButtonText }}
                    </strong>
                  </VBtn></VCol
                >
                <VCol class="ma-0 pa-0" cols="4">
                  <VBtn
                    size="small"
                    rounded="xl"
                    :color="showPeriod === 'Last 7D' ? 'primary' : 'blueTint'"
                    elevation="0"
                    :outlined="tokenBtnOutline"
                    class="w-100 text-none text-body-2"
                    @click="showWeekly(deviceTokens.weekly)"
                  >
                    <strong :class="showPeriod === 'Last 7D' ? 'text-background' : 'text-primary'">
                      {{ last7DButtonText }}
                    </strong>
                  </VBtn></VCol
                >
                <VCol class="ma-0 pa-0" cols="4">
                  <VBtn
                    size="small"
                    rounded="xl"
                    :color="showPeriod === 'Last 30D' ? 'primary' : 'blueTint'"
                    elevation="0"
                    :outlined="tokenBtnOutline"
                    class="w-100 text-none text-body-2"
                    @click="showMonthly(deviceTokens.monthly)"
                  >
                    <strong :class="showPeriod === 'Last 30D' ? 'text-background' : 'text-primary'">
                      {{ last30DButtonText }}
                    </strong>
                  </VBtn></VCol
                >
              </VRow>
            </VSheet>
          </VSheet>
          <div class="my-3 d-flex justify-space-between align-end">
            <div>
              <div class="text-body-2 text-darkGrey">
                {{
                  showPeriod === 'Latest' ? timestamp : `${tokensFromDateTs} - ${tokensToDateTs}`
                }}
              </div>
              <div class="text-darkestBlue font-weight-bold" style="font-size: 1.375rem">
                {{ actualReward }}
              </div>
            </div>

            <VSheet
              :color="selectPercentageBadgeColor(rewardScore)"
              class="d-flex align-center flex-shrink-1 flex-grow-0 text-caption font-weight-bold py-1 px-2 text-darkestBlue"
              rounded="xl"
            >
              <div style="width: 20px; height: 20px" class="d-flex align-center justify-center">
                <i
                  v-if="100 - rewardScore === 0"
                  class="fa-solid fa-badge-check"
                  style="font-size: 13px"
                ></i>
                <i
                  v-else
                  class="fa-solid fa-triangle-exclamation"
                  style="font-size: 13px"
                  :class="
                    100 - rewardScore >= 1 && 100 - rewardScore <= 29
                      ? 'text-warning'
                      : 'text-error'
                  "
                ></i>
              </div>
              <span class="ms-1 text-text">
                {{ 100 - rewardScore === 0 ? `Got 100%` : `Lost ${100 - rewardScore}%` }}</span
              >
            </VSheet>
          </div>
          <div class="pt-2">
            <div class="d-flex align-center justify-space-between">
              <div class="d-flex align-start">
                <span
                  style="width: 24px; height: 24px"
                  class="d-flex align-center justify-center"
                  :style="{ color: validationScoreColor }"
                >
                  <i class="fa-regular fa-hexagon fa-rotate-90 fa-lg"></i>
                </span>
                <div class="ms-1 text-caption">
                  <div class="text-text">{{ (rewardScore / 100).toFixed(2) }}</div>
                  <div class="text-darkGrey d-flex align-center">
                    <span>{{ rewardScoreText }}</span>
                    <span
                      style="width: 30px; height: 30px"
                      class="d-flex align-center justify-center"
                    >
                      <TooltipComponent
                        :message="rewardScoreTooltipMessage"
                        :container="'any'"
                        :tooltip-title="rewardScoreTooltipTitle"
                      />
                    </span>
                  </div>
                </div>
              </div>
              <div class="d-flex align-start gap-1">
                <span
                  style="width: 24px; height: 24px"
                  class="d-flex align-center justify-center text-mediumGrey"
                >
                  <i class="fa-regular fa-hexagon fa-rotate-90 fa-lg"></i>
                </span>

                <div class="ms-1 text-caption">
                  <div class="text-text">{{ periodMaxReward }}</div>
                  <div class="text-darkGrey d-flex align-center">
                    <span>{{ maxRewardsText }}</span>
                    <span
                      style="width: 30px; height: 30px"
                      class="d-flex align-center justify-center"
                    >
                      <TooltipComponent
                        :message="maxRewardTooltipMessage"
                        :container="'any'"
                        :tooltip-title="maxRewardTooltipTitle"
                      />
                    </span>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="my-3">
            <div class="d-flex justify-space-between">
              <div
                v-for="(item, index) in timelineColorsArray"
                :key="index"
                class="rounded-xl"
                style="height: 70px"
                :style="{ backgroundColor: `${item}`, width: calcedGraphWidth }"
              ></div>
            </div>
            <div
              v-if="showPeriod === 'Latest'"
              class="d-flex justify-space-between mt-1 text-caption text-text"
            >
              <div>00:00</div>
              <div>12:00</div>
              <div>23:00</div>
            </div>
            <div v-else class="d-flex justify-space-between mt-1 text-caption text-text">
              <div>{{ tokensFromDateTs }}</div>
              <div>{{ tokensToDateTs }}</div>
            </div>
          </div>
          <div class="d-flex text-caption align-center justify-center">
            <div v-if="showPeriod === 'Latest'" class="text-darkGrey">{{ timelineTs }}</div>
            <div v-else class="text-darkGrey">
              {{ tokensTimelinePeriod }}
            </div>
            <div>
              <span style="width: 30px; height: 30px" class="d-flex align-center justify-center">
                <TooltipComponent
                  :message="timelineTooltipMessage"
                  :container="'any'"
                  :tooltip-title="timelineTooltipTitle"
              /></span>
            </div>
          </div>
        </VSheet>
      </VCardText>
    </VCard>
    <RewardsMessage />
  </div>
</template>
