name: CD production

on:
  push:
    tags:
    - "[0-9]+.[0-9]+.[0-9]+"

env:
  SHORT_SHA: $(echo ${{ github.sha }} | cut -c 1-7)

concurrency:
  group: production-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  deploy:
    name: Build and publish to production
    runs-on: ubuntu-latest
    steps:
    - name: Clone
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build docker image
      env:
        IMAGE_REPO: ${{ secrets.IMAGE_REPOSITORY }}
      run: |
        export SHELL=/bin/bash
        DOCKER_BUILDKIT=1 docker build -t ${{ env.IMAGE_REPO }}:${{ env.SHORT_SHA }} .
        docker push ${{ env.IMAGE_REPO }}:${{ env.SHORT_SHA }}

    - name: Checkout argcod repo
      uses: actions/checkout@v4
      env:
        GH_ACCESS_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        repository: WeatherXM/platform-argocd
        token: ${{ env.GH_ACCESS_TOKEN }}
        path: argocd

    - name: Update production argocd app definitions
      env:
        IMAGE_REPO: ${{ secrets.IMAGE_REPOSITORY }}
        ARGOCD_APP_NAME: ${{ secrets.ARGOCD_APP_NAME }}
      run: |
        export SHELL=/bin/bash
        cd argocd
        ./scripts/update_app_image.py production ${{ env.ARGOCD_APP_NAME }} ${{ env.IMAGE_REPO }}:${{ env.SHORT_SHA }}

    - name: Promote to production PR
      uses: peter-evans/create-pull-request@v7
      env:
        GH_ACCESS_TOKEN: ${{ secrets.GH_TOKEN }}
        ARGOCD_APP_NAME: ${{ secrets.ARGOCD_APP_NAME }}
      with:
        repository: WeatherXM/platform-argocd
        token: ${{ env.GH_ACCESS_TOKEN }}
        path: argocd
        labels: production, automated
        commit-message: update ${{ env.ARGOCD_APP_NAME }} to ${{ github.sha }}
        title: "[production] update ${{ env.ARGOCD_APP_NAME }} to ${{ github.sha }}"
        body: Production update ${{ env.ARGOCD_APP_NAME }} to ${{ github.sha }}
        branch: ${{ env.ARGOCD_APP_NAME }}_staging
