name: Flow for PRs

on:
  pull_request:
    types: [ opened, reopened, synchronize ]
    branches:
    - 'develop'
    - 'main'

env:
  SHORT_SHA: $(echo ${{ github.sha }} | cut -c 1-7)

concurrency:
  group: pr-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  perform_local_tests:
    name: Build container images
    runs-on: ubuntu-latest

    steps:
    # fetch the code of the repo
    - name: Clone
      uses: actions/checkout@v4

    - name: Build the respective container images
      run: |
        export SHELL=/bin/bash
        docker build -t dev/dev:dev .
